language: java
jdk:
  - oraclejdk8
before_install:
  - git clone --branch=develop https://github.com/DTL-FAIRData/FairMetadata.git ~/FairMetadata
  - cd ~/FairMetadata
  - mvn install
  - cd $TRAVIS_BUILD_DIR
after_success:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent test org.jacoco:jacoco-maven-plugin:report coveralls:report
