swagger: '2.0'
info:
  version: 0.1.0
  title: FAIR Data Point Service
  description: >
    #### Echos back every URL, method, parameter and header

    Feel free to make a path or an operation and use **Try Operation** to test
    it. The echo server will

    render back everything.
schemes:
  - http
basePath: /
produces:
  - text/turtle
host: localhost:8080
paths:
  /:
    get:
      description: This endpoint returns information about the FAIR Data Point.
      operationId: getFdpMetadata
      responses:
        '200':
          description: FAIRDataPointMetadata
  /catalog:
    get:
      description: This endpoint returns a curated collection of metadata (catalog) about data sets available through the FAIR Data Point.
      operationId: getCatalogMetadata
      responses:
        '200':
          description: CatalogMetadata
  /catalog/{dataset}:
    parameters:
      - name: dataset
        in: path
        description: dataset ID
        type: string
        default: breedb
        required: true
    get:
      description: This endpoint returns information about a data set available through the FAIR Data Point.
      operationId: getDatasetMetadata
      responses:
        '200':
          description: DatasetMetadata
