swagger: '2.0'
info:
  version: 0.1.0
  title: FAIR Data Point Service
  description: >
    #### Echos back every URL, method, parameter and header

    Feel free to make a path or an operation and use **Try Operation** to test
    it. The echo server will

    render back everything.
schemes:
  - http
host: mazimi-prod.apigee.net
basePath: /
paths:
  /:
    get:
      description: This endpoint returns information about the FAIR Data Point.
      responses:
        '200':
          description: FAIRDataPointMetadata
  /catalog:
    get:
      description: This endpoint returns a curated collection of metadata (catalog) about data sets available through the FAIR Data Point.
      responses:
        '200':
          description: CatalogMetadata
  '/catalog/{dataset}':
    parameters:
      - name: dataset
        in: path
        description: dataset ID
        type: string
        required: true
    get:
      description: This endpoint returns information about a data set available through the FAIR Data Point.
      responses:
        '200':
          description: DatasetMetadata
