# valid store type options {1 = inMemoryStore, 2 = NativeStore, 3 = AllegroGraph, 4 = graphDB, 5 = blazegraph}
store:
    type: 1
    agraph:
        url: http://localhost:10035/repositories/fdp
        username: user
        password: password
    graphDb:
        url: http://localhost:7200
        repository: test
    blazegraph:
        url: http://localhost:8079/blazegraph
        repository: fdp    
    native:    
        dir: /tmp/fdp-store/
urlPath:
    root: /fdp
metadataProperties:
    rootSpecs: https://www.purl.org/fairtools/fdp/schema/0.1/fdpMetadata
    catalogSpecs: https://www.purl.org/fairtools/fdp/schema/0.1/catalogMetadata
    datasetSpecs: https://www.purl.org/fairtools/fdp/schema/0.1/datasetMetadata
    distributionSpecs: https://www.purl.org/fairtools/fdp/schema/0.1/distributionMetadata   
    publisherURI: http://localhost
    publisherName: localhost
    language: http://id.loc.gov/vocabulary/iso639-1/en
    license: http://rdflicense.appspot.com/rdflicense/cc-by-nc-nd3.0    
    accessRightsDescription: This resource has no access restriction 
fairSearch:
    fdpSubmitUrl: http://localhost:8080/fse/submitFdp
threadPoolSize: 4
metadataMetrics:
    https://purl.org/fair-metrics/FM_F1A: https://www.ietf.org/rfc/rfc3986.txt
    https://purl.org/fair-metrics/FM_A1.1: https://www.wikidata.org/wiki/Q8777

# Valid pidSystem type options {1 = default PIDSystem, 2 = purl.org PIDSystem}      
pidSystem:
    type: 1
    purl:
        baseUrl: http://purl.org/YOUR-PURL-DOMAIN/fdp
