# valid store type options {1 = inMemoryStore, 2 = NativeStore, 3 = AllegroGraph, 4 = graphDB, 5 = blazegraph}
store:
    type: 1
    agraph:
        url: http://localhost:10035/repositories/fdp
        username: test
        password: tester
    graphDb:
        url: http://localhost:7200
        repository: test
    blazegraph:
        url: http://localhost:8079/blazegraph
        repository: fdp    
    native:    
        dir: /tmp/fdp-store/
urlPath:
    root: /fdp
metadataProperties:
    rootSpecs: http://rdf.biosemantics.org/fdp/shex/fdpMetadata
    catalogSpecs: http://rdf.biosemantics.org/fdp/shex/catalogMetadata
    datasetSpecs: http://rdf.biosemantics.org/fdp/shex/datasetMetadata
    distributionSpecs: http://rdf.biosemantics.org/fdp/shex/distributionMetadata   
    publisherURI: http://dtls.nl
    publisherName: dtls
    language: http://id.loc.gov/vocabulary/iso639-1/en
    license: http://rdflicense.appspot.com/rdflicense/cc-by-nc-nd3.0    
    accessRightsDescription: This resource has no access restriction 
fairSearch:
    fdpSubmitUrl: http://localhost:8080/fse/submitFdp
threadPoolSize: 4
metadataMetrics:
    https://purl.org/fair-metrics/FM_F1A: https://www.ietf.org/rfc/rfc3986.txt
    https://purl.org/fair-metrics/FM_F1B: http://example.com/THIS_IS_A_PH_URI_4_ID_PERSISTENCE
    https://purl.org/fair-metrics/FM_A1.1: https://www.wikidata.org/wiki/Q8777
    https://purl.org/fair-metrics/FM_A2: http://example.com/THIS_IS_A_PH_URI_4_MD_LONGEVITY

# Valid pidSystem type options {1 = default PIDSystem, 2 = purl.org PIDSystem}      
pidSystem:
    type: 2
    purl:
        baseUrl: http://purl.org/biosemantics-lumc/fdp
